language: go
go:
  - 1.13.x
  - 1.12.x
  - tip
env:
  - GO111MODULE=on
install:
  - make dependency
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - go: tip
